version: '3'

networks:
    laravel:
    
services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: laravel_php
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
        networks:
            - laravel

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: laravel_nginx
        image: nginx
        ports:
            - 8081:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - laravel

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        container_name: laravel_mysql
        image: mysql:8.0
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db_name
            MYSQL_USER: laravel_db_user
            MYSQL_PASSWORD: laravel_db_pass
            
        networks:
            - laravel

    ####################################################################################################
    # PHPMyAdmin Service
    ####################################################################################################

    phpmyadmin:
        container_name: laravel_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8008:80
        links:
            - db:db
        environment:
            MYSQL_USER: laravel_db_user
            MYSQL_PASSWORD: laravel_db_pass
            MYSQL_ROOT_PASSWORD: root
            UPLOAD_LIMIT: 3000000000 

        networks:
            - laravel  

    ####################################################################################################
    # Node NPM Service
    ####################################################################################################

    nodenpm:
        image: node:16
        container_name: laravel_npm
        user: "1000:1000"
        volumes:
            - .:/var/www
        working_dir: /var/www
        entrypoint: ['npm']
        networks:
            - laravel

    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    # db:
    #     container_name: laravel_mariadb
    #     image: mariadb:10.11
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - .docker/db/data:/var/lib/mysql
    #         - .docker/logs:/var/log/mysql
    #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: laravel_db_name
    #         MYSQL_USER: laravel_db_user
    #         MYSQL_PASSWORD: laravel_db_pass
